# Revisiting The January Effect

## Introduction
In this article, we review the January effect which proposes that stock prices' increase from December to January is the highest.
Sources of this calendar effect include tax-loss harvesting by selling losing stocks, and window dressing by buying (selling) winning (losing) stocks.
We could profit from the January effect with a simple mean-reverting trading strategy, that is buy (sell) the losing (winning) stocks at the end of the calendar year. 

The project is shared on my online repository https://github.com/DinodC/january-effect.

Import packages

In [1]:
import numpy as np
import pandas as pd
import pickle

Magic

In [2]:
%matplotlib inline

## Pull Data

In this section, we collect S&P consittuents' historical data from a previous project https://quant-trading.blog/2019/06/24/backtesting-a-trading-strategy-part-2/.

In [3]:
keys = ['sp500',
        'sp400',
        'sp600']

Initialize close

In [4]:
close = {}

Pull data

In [5]:
for i in keys:
    # Load OHLCV data
    with open(i + '_data.pickle', 'rb') as f:
        data = pickle.load(f)

    # Update close prices data
    close[i] = data.close
    
    f.close()

Inspect close prices of S&P 500 Index

In [6]:
close['sp500'].head()

Symbols,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS
date,,,,,,,,,,,,,,,,,,,,,
2014-06-11,40.1199,40.2868,125.0694,86.0249,45.0769,66.4223,22.92,35.9633,74.9719,67.46,...,25.6691,40.9150,84.1321,46.6073,28.8084,35.4555,51.7899,101.5068,28.0164,30.9798
2014-06-12,39.7726,38.2958,123.2252,84.5860,44.6031,65.9975,23.03,35.7925,74.5018,66.56,...,25.8547,41.1019,83.8928,46.4230,28.5372,35.2780,51.2950,101.0367,27.7535,30.8448
2014-06-13,39.8407,38.4672,123.7407,83.6603,45.0187,66.2930,22.95,35.7745,74.7820,66.82,...,25.8884,41.6091,84.7098,46.3744,28.4920,36.0532,51.5945,101.2861,27.8192,30.9702
2014-06-16,39.7181,39.1150,124.0086,84.5035,44.8857,66.0529,23.27,35.8734,74.8634,67.62,...,26.0740,41.9028,84.9326,46.4424,28.3791,35.9318,51.5099,100.7105,27.4060,30.9798
2014-06-17,40.0927,39.8867,124.9411,84.3935,45.1351,66.2561,23.43,35.8375,74.5832,67.54,...,26.0910,42.2409,84.5200,46.2677,28.8310,36.0346,51.7639,100.4707,27.9601,31.6355

In [7]:
close['sp500'].tail()

Symbols,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS
date,,,,,,,,,,,,,,,,,,,,,
2019-06-04,67.95,29.12,154.61,179.64,76.75,82.21,267.06,77.46,177.97,268.71,...,57.78,106.90,73.59,54.40,33.30,77.40,106.97,117.41,44.40,108.12
2019-06-05,68.35,30.36,154.61,182.54,77.06,81.65,268.80,78.69,179.56,272.86,...,59.32,105.60,72.98,55.38,33.42,78.88,107.29,118.54,44.18,108.50
2019-06-06,69.16,30.38,154.90,185.22,77.07,81.75,269.19,80.09,180.40,274.80,...,59.80,106.01,74.31,55.63,34.03,79.15,108.42,120.31,44.24,108.89
2019-06-07,69.52,30.92,155.35,190.15,77.43,83.48,267.87,80.74,182.92,278.16,...,59.43,107.49,74.58,55.94,34.16,79.56,109.07,120.73,43.64,110.06
2019-06-10,70.29,30.76,153.52,192.58,76.95,84.77,272.43,81.27,184.44,280.34,...,59.26,110.88,74.91,57.10,34.69,80.38,108.65,121.71,43.84,110.22

In [8]:
close['sp500'].describe()

Symbols,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS
count,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,...,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000
mean,52.010924,41.207727,145.418612,135.094399,66.653293,84.553883,162.741109,49.113396,118.473403,142.243243,...,39.351443,58.850843,75.442714,53.174206,26.877544,51.296575,66.602743,111.697803,36.704361,59.798250
std,13.866577,6.366236,24.128339,38.127616,17.721243,9.483389,116.577717,12.653128,31.189929,70.413470,...,8.322974,22.240068,4.717698,7.833835,3.222176,16.349757,15.997628,9.929764,10.736900,20.223068
min,32.258600,24.539800,79.168700,82.743800,42.066600,65.718100,22.220000,33.935700,68.852300,60.880000,...,25.247700,32.502600,58.967500,34.178400,18.532600,28.874500,44.181800,89.236100,18.885300,30.652000
25%,39.393500,36.586125,132.519725,103.622650,53.170800,77.738125,80.662500,39.405975,92.616475,82.092500,...,31.485800,42.102950,72.534125,48.731800,24.215550,35.033175,53.060925,103.343675,26.826025,44.749325
50%,46.097600,40.843300,150.457700,119.473800,58.470800,83.840300,118.550000,43.040600,112.097050,107.945000,...,39.055650,52.368850,75.817000,54.521200,26.573400,48.085300,61.564200,112.761500,38.198900,51.333600
75%,65.591850,46.119900,161.899875,167.841200,82.894300,89.847025,261.935000,58.171250,149.591750,212.247500,...,45.444750,68.789375,78.491000,59.650550,29.650500,67.341800,80.202225,119.131625,46.431025,80.809150
max,81.940000,57.586600,199.159900,229.392000,116.445400,107.649700,449.750000,81.270000,184.440000,289.250000,...,59.800000,139.263300,86.137400,67.795300,35.000000,83.549000,109.070000,130.912800,57.139500,110.220000

In [9]:
close['sp500'].shape

(1258, 505)

## The January Effect
A calendar effect is an economic or stock market behavior which is related to the calendar such as the day of the week or the month of the year.
The most popular is the January effect which suggests that stock prices' increase from December to January is the highest.
The January effect was first observed by Sydney Wachtel in 1942, but seems to have lost its effect in recent years.

## Explanations Of The January Effect:
Possible explanations of the January effect include:
1. Tax-loss harvesting (or saving): 
Tax-loss harvesting allows investors to save taxes on realized gains using their unrealized losses.
In detail, investors sell the the losing stocks of their portfolio to generate losses.
Investors' taxes are reduced as the gains and losses are netted out.
2. Window dressing: 
Window dressing enables investors to improve the appearance of the portfolios which they manage.
In detail, investors buy (sell) winning (losing) stocks to enhance portfolio appearance.
Investors' portfolios has a better image as they now contain high-flying stocks.
3. Bonus: 
Bonus (end-of-year) allows investors to purchase stocks at the beginning of the year.
In detail, investors buying stocks in January will push the stock prices up.
Investors' bonus fuels price increase from December to January.

## A Trading Strategy To Profit From The January Effect
A possible trading strategy to profit from the January effect is the following:
1. Buy the losing (or off-loaded) stocks of December; and
2. Sell the winning stocks of December.

We implement the strategy using the different investment universes:
1. S&P 500 Index composed of large capitalization stocks
2. S&P 400 Index comprised of medium capitalization stocks
3. S&P 600 Index composed of small capitalization stocks

Assume transaction cost (one-way)

In [10]:
tc_one_way = 0.0005

Initialize the strategy's returns

In [11]:
returns = {}

Calculate the portfolio returns

In [12]:
for i in keys:
    # Create today series
    today = pd.Series(close[i].index)
    
    # Create months and years series
    months = pd.Series(close[i].index.month)
    years = pd.Series(close[i].index.year)
    
    # Create next day of the month and next day of the year
    next_day_month = months.shift(periods=-1)
    next_day_year = years.shift(periods=-1)
    
    # Last day of December
    mask_last_day_dec = (months==12) & (next_day_month==1)
    last_day_dec = today[mask_last_day_dec]
    
    # Last day of Jan
    mask_last_day_jan = (months==1) & (next_day_month==2)
    last_day_jan = today[mask_last_day_jan]
    
    # Ensure that last day of January is after last day of December
    assert (last_day_jan.values > last_day_dec.values).any(), 'Assertion violated'
    
    # End of year indices
    mask_eoy = (years!=next_day_year)
    eoy = today[mask_eoy]
    # Last item is not eoy
    eoy = eoy[:-1]
    
    # Check that eoy dates match last day of December dates
    assert (last_day_dec.values==eoy.values).any(), 'Assertion violated'
    
    # Calculate annual returns (from December of previous year to December of current year)
    annual_returns = close[i][mask_eoy.values].pct_change()
    
    # Retrieve last day of January close prices
    close_last_day_jan = close[i][mask_last_day_jan.values]
    
    # Retrieve last day of December close prices
    close_last_day_dec = close[i][mask_last_day_dec.values]
    # Modify the index of clost_last_day_dec 
    close_last_day_dec.index = close_last_day_jan.index
    
    # Calculate January returns (from December of previous year to January of current year)
    january_returns = (close_last_day_jan - close_last_day_dec) / close_last_day_dec
    
    for j in range(1, annual_returns.shape[0]-1):
        # Create a mask for stocks with returns != NaN
        mask_has_data = np.isfinite(annual_returns.iloc[j, :])
        has_data = list(mask_has_data[mask_has_data].index)

        # Sort stocks as per annual returns
        sort_tickers = annual_returns[has_data].iloc[j, :].sort_values().index

        # Set the number of stocks to long (short)
        top_n = round(len(has_data) / 10)

        # List of stocks to long and short
        longs = sort_tickers[:top_n]
        shorts = sort_tickers[-top_n:]

        # Calculate returns from the last day of December to the last day of January
        long_returns = (january_returns.iloc[j][longs]).mean()
        short_returns = (january_returns.iloc[j][shorts]).mean()
        portfolio_returns = 0.5 * (long_returns - short_returns) - 2 * tc_one_way

        # Update portfolio returns
        returns[i] = portfolio_returns

In [23]:
0.5 * ((january_returns.iloc[j][longs]).mean() - (january_returns.iloc[j][shorts]).mean() ) - 2 * tc_one_way

0.0674128880306187

Display the strategy returns

In [13]:
pd.DataFrame(returns, 
            index=['returns'],
            columns=keys)

            sp500     sp400     sp600
returns  0.048986  0.063328  0.067413

Remarks:
1. The trading strategy generated positive returns under all investment universes.
2. The trading strategy produced the highest (lowest) returns using small (large) capitalization stocks.
3. Note that higher spreads are usually attached to small-cap stocks which could reduce the trading strategy's returns.

## Conclusion
...

...

...